version: "3"

services:

  postgres:
    image: postgres:11.6-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 9090:8080
    depends_on:
      - postgres
